version: '3'
services:
  # mysql:
  #   image: mysql:8.0
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: P@ssw0rd
  #     MYSQL_USER: product_user
  #     MYSQL_PASSWORD: product_user_password
  #     MYSQL_DATABASE: product

  msmusic:
      container_name: msmusic-container
      image: msmusic-image
      build: .
      ports:
        - "8080:8080"

      # environment:
      #   SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/product
      #   SPRING_DATASOURCE_USERNAME: product_user
      #   SPRING_DATASOURCE_PASSWORD: product_user_password

  frontend:
      container_name: frontend-container
      image: frontend-image
      build:
        context: .
        dockerfile: src/main/frontend/Dockerfile
      ports:
        - "3000:3000"